backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: blog
    label: Vacantes
    folder: source/vacantes/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{title}}'
    fields:
      - {label: Pro, name: "Pro", widget: "boolean", default: true}
      - {label: Titulo, name: title, widget: string}
      - {label: Empresa, name: company, widget: string}
      - {label: Página Web, name: company_url, widget: string}
      - {label: Logotipo, name: company_logo, widget: image, default: "/uploads/chocolate-dogecoin.jpg"}
      - {label: Dia de Publicación, name: date, widget: date, format: "MMM DD YY"}
      - {label: Pais, name: country, widget: select, options: ["Argentina", "Bolivia", "Brasil", "Chile", "Colombia", "Costa Rica", "Cuba", "Ecuador", "El Salvador", "Guayana Francesa", "Granada", "Guatemala",  "Guayana", "Haití", "Honduras", "Jamaica", "México", "Nicaragua", "Paraguay", "Panamá", "Perú", "Puerto Rico", "República Dominicana",  "Uruguay", "Venezuela" ]}
      - {label: Estado, name: state, widget: string}
      - {label: Tipo de Vacante, name: job_type, widget: select, options: ["Tiempo Completo", "Medio Tiempo", "Intership", "Freelance"]}
      - {label: Categorías, name: categories, widget: "list", allow_add: false, default: ["diseño"]}
      - {label: Email, name: email, widget: string}
      - {label: URL Aplicación, name: apply_url, widget: string, required: false}
      - {label: Descripción, name: body, widget: markdown}