backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: blog
    label: Vacantes
    folder: source/vacantes/
    extension: .html.md
    format: frontmatter
    create: true
    slug: '{{year}}-{{title}}'
    fields:
      - {label: "Pro", name: "Pro", widget: "boolean", default: true}
      - {label: Titulo, name: title, widget: string}
      - {label: Empresa, name: company, widget: string}
      - {label: Página Web, name: company_url, widget: string}
      - {label: Logotipo, name: company_logo, widget: image, default: "/uploads/chocolate-dogecoin.jpg"}
      - {label: Dia de Publicación, name: date, widget: datetime}
      - {label: Pais, name: country, widget: select, options: ["México", "Argentina", "Brasil"]}
      - {label: Estado, name: state, widget: string}
      - {label: Type, name: job_type, widget: select, options: ["Tiempo Completo", "Medio Tiempo", "Intership", "Freelance"]}
      - {label: Category, name: categories, widget: "list", allow_add: false, default: ["diseño"]}
      - {label: Email, name: email, widget: string}
      - {label: Detalles, name: apply_url, widget: string}
      - {label: Descripción, name: body, widget: markdown}